version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "80:80"
      - "443:443"  # Добавляем HTTPS порт
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем сертификаты
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - server
    restart: unless-stopped