version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./client/dist:/usr/share/nginx/html  # Только для разработки!
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

    server:
      build: 
        context: ./proxy
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - NODE_ENV=production
      restart: unless-stopped
      volumes:
        - ./proxy:/app
        - /app/node_modules
      networks:
        - app-network

networks:
  app-network:
    driver: bridge