version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:80"  # Фронтенд будет доступен на 80 порту
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "3000:3000"  # Бэкенд будет доступен на 3000 порту
    environment:
      - NODE_ENV=production
    restart: unless-stopped